@Service_HostAddress = http://localhost:8080

GET {{Service_HostAddress}}/
Accept: application/json

###

GET {{Service_HostAddress}}/Vertex%20AI
Accept: application/json

###


POST {{Service_HostAddress}}/v1/projects/{{project}}/locations/{{region}}/publishers/google/models/{{model}}:generateContent
Content-Type: application/json

{
    "model": "{{model}}",
    "contents": [
        { 
            "role": "user",
            "parts": [{ "text": "Hello there!" }]
        }
    ],
    "generationConfig": {
        "thinkingConfig": {
            "thinkingBudget": 0
        }
    }
}

###

POST {{Service_HostAddress}}/v1/projects/{{project}}/locations/{{region}}/publishers/google/models/{{model}}:streamGenerateContent
Content-Type: application/json

{
    "model": "{{model}}",
    "contents": [
        { 
            "role": "user",
            "parts": [{ "text": "Hello there!" }]
        }
    ],
    "generationConfig": {
        "thinkingConfig": {
            "thinkingBudget": 0
        }
    }
}

###

